# Generated by Django 5.0.4 on 2024-05-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_plus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_plus',
            name='about_user',
            field=models.TextField(null=True),
        ),
    ]
