# Generated by Django 5.0.4 on 2024-05-20 09:19

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_user_plus_about_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_plus',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 300], upload_to='avatars'),
        ),
    ]
