# Generated by Django 5.0.4 on 2024-05-20 10:50

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_user_plus_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_plus',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='I also use this website', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='avatars'),
        ),
    ]
