# Generated by Django 5.0.4 on 2024-05-20 10:58

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_alter_user_plus_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_plus',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='avatars/default-avatar-profile-icon-of-social-media-user-vector.jpg', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='avatars'),
        ),
    ]
